name: Report an issue with @svelteuidev/ scoped package
description: Tell us if something is not working as expected
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for reaching out!
        Before submitting an issue please make sure that you use latest version of all @svelteuidev/ packages.
  - type: dropdown
    id: version
    attributes:
      label: What package has an issue
      options:
        - '@svelteuidev/core'
        - '@svelteuidev/composables'
        - '@svelteuidev/motion'
        - '@svelteuidev/dates'
        - '@svelteuidev/preprocessors'
        - '@svelteuidev/prism'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: A clear and concise description of what the bug is
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: In which browser(s) did the problem occur?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Firefox Beta/Dev/Nightly
        - Chrome Beta/Dev/Canary
        - Safari Beta
        - Microsoft Edge Beta/Dev/Canary
        - Other - list in description
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '....'
        2. Click on '....'
        3. Scroll down to '....'
        4. See the error
    validations:
      required: true
  - type: dropdown
    id: fix
    attributes:
      label: Do you know how to fix the issue
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: dropdown
    id: participate
    attributes:
      label: Are you willing to participate in fixing this issue and create a pull request with the fix
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant Assets
      description: |
        A list of assets (errors, screenshots) relevant to this bug.

        Tip: You can attach images or log files by highlighting this area and dragging files into it.
      placeholder: |
        To access the site's log, press Ctrl + Shift + I and open the console tab.
        Errors will be highlighted in red.
